
"use client"

import * as React from "react"
import { Globe } from "lucide-react"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import { Button } from "@/components/ui/button"

const languages = [
  { name: "English", code: "en" },
  { name: "Arabic", code: "ar" },
  { name: "French", code: "fr" },
  { name: "Portuguese", code: "pt" },
  { name: "Spanish", code: "es" },
  { name: "Swahili", code: "sw" },
]

export function LanguageSwitcher() {
  const [mounted, setMounted] = React.useState(false)
  const [currentLang, setCurrentLang] = React.useState(languages[0])

  React.useEffect(() => {
    setMounted(true)
  }, [])

  // To completely avoid hydration mismatches with dynamic IDs generated by Radix UI,
  // we render a simple placeholder button that doesn't trigger any complex markup
  // until the component is fully mounted on the client.
  if (!mounted) {
    return (
      <Button variant="ghost" size="sm" className="flex items-center gap-2 pointer-events-none opacity-50">
        <Globe className="h-4 w-4" />
        <span className="hidden md:inline">English</span>
      </Button>
    )
  }

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="ghost" size="sm" className="flex items-center gap-2">
          <Globe className="h-4 w-4" />
          <span className="hidden md:inline">{currentLang.name}</span>
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        {languages.map((lang) => (
          <DropdownMenuItem
            key={lang.code}
            onClick={() => setCurrentLang(lang)}
            className="cursor-pointer"
          >
            {lang.name}
          </DropdownMenuItem>
        ))}
      </DropdownMenuContent>
    </DropdownMenu>
  )
}
