
"use client"

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'EN' | 'FR' | 'AR' | 'SW' | 'PT'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  EN: {
    about: "About",
    pillars: "Pillars",
    program: "Program",
    pastEvents: "Past Events",
    gallery: "Gallery",
    team: "Team",
    register: "Register",
    registerNow: "Register Now",
    conferenceName: "International Pan African Youth Conference 2026",
    heroSubtitle: "Uniting Pan-African youth for a just, inclusive, and sustainable continent. Together towards 2063.",
    reimagining: "REIMAGINING",
    africas: "AFRICA\\'S",
    future: "FUTURE",
    visionTitle: "The Vision",
    visionHeadline: "Translating Potential Into Actionable Power",
    visionDescription: "The African Union Students' Platform (AUSP) is a continental community spanning over 46 African countries. With 70% of the continent under 30, this conference is the catalyst to translate youth energy into systemic change.",
    roleTitle: "Our Role",
    roleHeadline: "Empowering the Continental Voice",
    roleDescription: "AUSP represents over 100 million students. Our mission is built on three unbreakable pillars: Education, Connection, and Empowerment.",
    statsCountries: "Countries",
    statsDelegates: "Delegates",
    statsImpact: "Impact",
    pillarsHeadline: "CORE PILLARS OF TRANSFORMATION",
    pillar1Title: "Economic Inclusion",
    pillar1Desc: "Bridging the wealth gap and creating sustainable opportunities for youth-led ventures.",
    pillar2Title: "Digital Innovation",
    pillar2Desc: "Leveraging technology to solve continental challenges and drive digital sovereignty.",
    pillar3Title: "Climate Action",
    pillar3Desc: "Leading the green revolution and protecting Africa's natural heritage for future generations.",
    teamTitle: "Our Team",
    teamHeadline: "Meet the Visionaries",
    teamSubtitle: "The dedicated individuals working tirelessly to shape the future of African youth leadership.",
    partners: "Partners",
    partnersTitle: "Our Trusted Partners & Sponsors",
    sponsorship: "Sponsorship",
    awards: "Awards",
    backToHome: "Back to Home",
    awardsTitle: "Excellence Awards 2026",
    awardsHeadline: "SMEGAfrica Excellence Awards 2026",
    awardsSubtitle: "Call for Nominations – Hosted by Scholar Media Africa",
    awardsIntro1: "The SMEGAfrica Excellence Awards 2026, hosted by Scholar Media Africa, are now officially open for nominations!",
    awardsIntro2: "This prestigious platform celebrates outstanding individuals, organizations, and innovators who are driving impact, transformation, and sustainable growth across Africa.",
    nominationPeriod: "Nomination Period",
    whoApply: "Who Should Apply?",
    whoApplyDesc: "Changemakers, entrepreneurs, student leaders, or institutions making a difference.",
    whyNominate: "Why Nominate?",
    whyNominate1: "Showcase your impact on a continental stage",
    whyNominate2: "Gain visibility among industry leaders and policymakers",
    whyNominate3: "Join a network of Africa’s most inspiring change agents",
    submitNomination: "Submit Your Nomination",
    attendDelegate: "Attend as a Delegate",
    attendDelegateDesc: "Not applying for an award? You can still be part of this impactful experience! The SMEGAfrica Conference brings together thought leaders, innovators, students, and professionals from across the continent for networking, learning, and collaboration.",
    delegateBenefits: "Delegate Benefits:",
    benefit1: "Access to high-level panel discussions & keynote sessions",
    benefit2: "Networking with industry leaders and policymakers",
    benefit3: "Insights into innovation, media, and entrepreneurship in Africa",
    benefit4: "Participation in the prestigious awards ceremony",
    registerDelegate: "Register as a Delegate",
    enquiries: "Enquiries",
    callUs: "Call Us",
    emailUs: "Email Us",
    securePayment: "Secure Payment",
    choosePayment: "Choose your preferred payment method to complete the registration.",
    paybillDetails: "M-Pesa Paybill Details:",
    payNow: "Pay Now",
    allTransactionsSecure: "All transactions are secure and encrypted.",
    creditCard: "Credit/Debit Card",
    bankTransfer: "Bank Transfer",
    mpesa: "M-Pesa",
    paypal: "PayPal",
    secureSeat: "Secure Your Seat",
    secureSeatSubtitle: "Be part of the reimagining. Choose your attendance path.",
    studentDelegate: "Student Delegate",
    generalAdmission: "General Admission",
    virtualDelegate: "Virtual Delegate",
    perkSessions: "Access to sessions",
    perkBag: "Delegate bag",
    perkCert: "Certificate",
    perkFullAccess: "Full session access",
    perkDinner: "Networking dinner",
    perkLunch: "Lunch & Snacks",
    perkStream: "Streaming access",
    perkWorkbook: "Digital workbook",
    perkECert: "E-Certificate",
    regDetails: "Registration Details",
    firstName: "First Name",
    lastName: "Last Name",
    emailAddress: "Email Address",
    country: "Country",
    organization: "Organization / University",
    dietary: "Dietary Requirements (Optional)",
    proceedPayment: "Proceed to Payment",
    regAgreement: "Payments are securely processed. Registration implies agreement to our Terms of use and Code of Conduct.",
    footerAbout: "Uniting African youth to drive sustainable development and global innovation. An initiative of the African Union Students' Platform.",
    quickLinks: "Quick Links",
    contactUs: "Contact Us",
    newsletter: "Newsletter",
    newsletterDesc: "Get the latest speaker updates and announcements.",
    emailPlaceholder: "Email Address",
    privacyPolicy: "Privacy policy",
    termsOfUse: "Terms of use",
  },
  FR: {
    about: "À propos",
    pillars: "Piliers",
    program: "Programme",
    pastEvents: "Événements passés",
    gallery: "Galerie",
    team: "Équipe",
    register: "S'inscrire",
    registerNow: "Inscrivez-vous maintenant",
    conferenceName: "Conférence Internationale de la Jeunesse Panafricaine 2026",
    heroSubtitle: "Unir la jeunesse panafricaine pour un continent juste, inclusif et durable. Ensemble vers 2063.",
    reimagining: "RÉIMAGINER",
    africas: "L'AVENIR DE L'AFRIQUE",
    future: "",
    visionTitle: "La Vision",
    visionHeadline: "Traduire le Potentiel en Pouvoir Actionnable",
    visionDescription: "La Plateforme des Étudiants de l'Union Africaine (AUSP) est une communauté continentale couvrant plus de 46 pays africains. Avec 70% du continent âgé de moins de 30 ans, cette conférence est le catalyseur pour traduire l'énergie de la jeunesse en changement systémique.",
    roleTitle: "Notre Rôle",
    roleHeadline: "Autonomiser la Voix Continentale",
    roleDescription: "L'AUSP représente plus de 100 millions d'étudiants. Notre mission repose sur trois piliers incassables : l'Éducation, la Connexion et l'Autonomisation.",
    statsCountries: "Pays",
    statsDelegates: "Délégués",
    statsImpact: "Impact",
    pillarsHeadline: "PILIERS CORE DE LA TRANSFORMATION",
    pillar1Title: "Inclusion Économique",
    pillar1Desc: "Combler l'écart de richesse et créer des opportunités durables pour les entreprises dirigées par des jeunes.",
    pillar2Title: "Innovation Numérique",
    pillar2Desc: "Tirer parti de la technologie pour résoudre les défis continentaux et stimuler la souveraineté numérique.",
    pillar3Title: "Action Climatique",
    pillar3Desc: "Mener la révolution verte et protéger le patrimoine naturel de l'Afrique pour les générations futures.",
    teamTitle: "Notre Équipe",
    teamHeadline: "Rencontrez les Visionnaires",
    teamSubtitle: "Les individus dévoués travaillant sans relâche pour façonner l'avenir du leadership de la jeunesse africaine.",
    partners: "Partenaires",
    partnersTitle: "Nos partenaires et sponsors de confiance",
    sponsorship: "Parrainage",
    awards: "Prix",
    backToHome: "Retour à l'accueil",
    awardsTitle: "Prix d'Excellence 2026",
    awardsHeadline: "Prix d'Excellence SMEGAfrica 2026",
    awardsSubtitle: "Appel à candidatures – Organisé par Scholar Media Africa",
    awardsIntro1: "Les SMEGAfrica Excellence Awards 2026, organisés par Scholar Media Africa, sont désormais officiellement ouverts aux nominations !",
    awardsIntro2: "Cette plateforme prestigieuse célèbre les individus, organisations et innovateurs exceptionnels qui stimulent l'impact, la transformation et la croissance durable à travers l'Afrique.",
    nominationPeriod: "Période de nomination",
    whoApply: "Qui devrait postuler ?",
    whoApplyDesc: "Acteurs du changement, entrepreneurs, leaders étudiants ou institutions faisant une différence.",
    whyNominate: "Pourquoi nominer ?",
    whyNominate1: "Présentez votre impact sur une scène continentale",
    whyNominate2: "Gagnez en visibilité auprès des leaders de l'industrie et des décideurs politiques",
    whyNominate3: "Rejoignez un réseau des agents de changement les plus inspirants d'Afrique",
    submitNomination: "Soumettez votre candidature",
    attendDelegate: "Participer en tant que délégué",
    attendDelegateDesc: "Vous ne postulez pas pour un prix ? Vous pouvez toujours faire partie de cette expérience percutante ! La conférence SMEGAfrica rassemble des leaders d'opinion, des innovateurs, des étudiants et des professionnels de tout le continent pour le réseautage, l'apprentissage et la collaboration.",
    delegateBenefits: "Avantages des délégués :",
    benefit1: "Accès à des tables rondes et des sessions plénières de haut niveau",
    benefit2: "Réseautage avec les leaders de l'industrie et les décideurs politiques",
    benefit3: "Aperçu de l'innovation, des médias et de l'entrepreneuriat en Afrique",
    benefit4: "Participation à la prestigieuse cérémonie de remise des prix",
    registerDelegate: "S'inscrire comme délégué",
    enquiries: "Demandes de renseignements",
    callUs: "Appelez-nous",
    emailUs: "Envoyez-nous un e-mail",
    securePayment: "Paiement sécurisé",
    choosePayment: "Choisissez votre mode de paiement préféré pour terminer l'inscription.",
    paybillDetails: "Détails du Paybill M-Pesa :",
    payNow: "Payer maintenant",
    allTransactionsSecure: "Toutes les transactions sont sécurisées et cryptées.",
    creditCard: "Carte de crédit/débit",
    bankTransfer: "Virement bancaire",
    mpesa: "M-Pesa",
    paypal: "PayPal",
    secureSeat: "Réservez votre place",
    secureSeatSubtitle: "Faites partie de la réinvention. Choisissez votre parcours de participation.",
    studentDelegate: "Délégué étudiant",
    generalAdmission: "Admission générale",
    virtualDelegate: "Délégué virtuel",
    perkSessions: "Accès aux sessions",
    perkBag: "Sac du délégué",
    perkCert: "Certificat",
    perkFullAccess: "Accès complet aux sessions",
    perkDinner: "Dîner de réseautage",
    perkLunch: "Déjeuner et collations",
    perkStream: "Accès au streaming",
    perkWorkbook: "Cahier d'exercices numérique",
    perkECert: "E-Certificat",
    regDetails: "Détails de l'inscription",
    firstName: "Prénom",
    lastName: "Nom de famille",
    emailAddress: "Adresse e-mail",
    country: "Pays",
    organization: "Organisation / Université",
    dietary: "Besoins alimentaires (facultatif)",
    proceedPayment: "Procéder au paiement",
    regAgreement: "Les paiements sont traités en toute sécurité. L'inscription implique l'acceptation de nos conditions d'utilisation et de notre code de conduite.",
    footerAbout: "Unir la jeunesse africaine pour stimuler le développement durable et l'innovation mondiale. Une initiative de la Plateforme des Étudiants de l'Union Africaine.",
    quickLinks: "Liens rapides",
    contactUs: "Contactez-nous",
    newsletter: "Bulletin",
    newsletterDesc: "Recevez les dernières mises à jour sur les conférenciers et les annonces.",
    emailPlaceholder: "Adresse e-mail",
    privacyPolicy: "Politique de confidentialité",
    termsOfUse: "Conditions d'utilisation",
  },
  AR: {
    about: "حول",
    pillars: "الأركان",
    program: "البرنامج",
    pastEvents: "الأحداث الماضية",
    gallery: "المعرض",
    team: "الفريق",
    register: "تسجيل",
    registerNow: "سجل الآن",
    conferenceName: "المؤتمر الدولي للشباب الأفريقي 2026",
    heroSubtitle: "توحيد الشباب الأفريقي من أجل قارة عادلة وشاملة ومستدامة. معاً نحو 2063.",
    reimagining: "إعادة تصور",
    africas: "مستقبل",
    future: "أفريقيا",
    visionTitle: "الرؤية",
    visionHeadline: "ترجمة الإمكانات إلى قوة عملية",
    visionDescription: "منصة طلاب الاتحاد الأفريقي (AUSP) هي مجتمع قاري يمتد لأكثر من 46 دولة أفريقية. مع وجود 70٪ من القارة تحت سن 30 ، يعد هذا المؤتمر هو المحفز لترجمة طاقة الشباب إلى تغيير جذري.",
    roleTitle: "دورنا",
    roleHeadline: "تمكين الصوت القاري",
    roleDescription: "تمثل AUSP أكثر من 100 مليون طالب. مهمتنا مبنية على ثلاث ركائز لا تقبل الكسر: التعليم ، والتواصل ، والتمكين.",
    statsCountries: "بلدان",
    statsDelegates: "المندوبين",
    statsImpact: "التأثير",
    pillarsHeadline: "الركائز الأساسية للتحول",
    pillar1Title: "الاشتمال الاقتصادي",
    pillar1Desc: "سد فجوة الثروة وخلق فرص مستدامة للمشاريع التي يقودها الشباب.",
    pillar2Title: "الابتكار الرقمي",
    pillar2Desc: "الاستفادة من التكنولوجيا لحل التحديات القارية ودفع السيادة الرقمية.",
    pillar3Title: "العمل المناخي",
    pillar3Desc: "قيادة الثورة الخضراء وحماية التراث الطبيعي لأفريقيا للأجيال القادمة.",
    teamTitle: "فريقنا",
    teamHeadline: "تعرف على أصحاب الرؤى",
    teamSubtitle: "الأفراد المكرسون الذين يعملون بلا كلل لتشكيل مستقبل قيادة الشباب الأفريقي.",
    partners: "الشركاء",
    partnersTitle: "شركاؤنا ورعاتنا الموثوق بهم",
    sponsorship: "رعاية",
    awards: "جوائز",
    backToHome: "العودة إلى الرئيسية",
    awardsTitle: "جوائز التميز 2026",
    awardsHeadline: "جوائز SMEGAfrica للتميز 2026",
    awardsSubtitle: "دعوة للترشيحات - تستضيفها Scholar Media Africa",
    awardsIntro1: "جوائز SMEGAfrica للتميز 2026، التي تستضيفها Scholar Media Africa، مفتوحة الآن رسمياً للترشيحات!",
    awardsIntro2: "تحتفل هذه المنصة المرموقة بالأفراد والمنظمات والمبتكرين المتميزين الذين يقودون التأثير والتحول والنمو المستدام في جميع أنحاء أفريقيا.",
    nominationPeriod: "فترة الترشيح",
    whoApply: "من يجب أن يتقدم؟",
    whoApplyDesc: "صناع التغيير، رواد الأعمال، القادة الطلابيون، أو المؤسسات التي تحدث فرقاً.",
    whyNominate: "لماذا تُرشح؟",
    whyNominate1: "اعرض تأثيرك على مسرح قاري",
    whyNominate2: "احصل على رؤية بين قادة الصناعة وصناع السياسات",
    whyNominate3: "انضم إلى شبكة من أكثر وكلاء التغيير إلهاماً في أفريقيا",
    submitNomination: "قدم ترشيحك",
    attendDelegate: "احضر كمندوب",
    attendDelegateDesc: "لا تتقدم بطلب للحصول على جائزة؟ لا يزال بإمكانك أن تكون جزءاً من هذه التجربة المؤثرة! يجمع مؤتمر SMEGAfrica قادة الفكر والمبتكرين والطلاب والمهنيين من جميع أنحاء القارة للتواصل والتعلم والتعاون.",
    delegateBenefits: "مزايا المندوبين:",
    benefit1: "الوصول إلى حلقات نقاش رفيعة المستوى وجلسات رئيسية",
    benefit2: "التواصل مع قادة الصناعة وصناع السياسات",
    benefit3: "رؤى حول الابتكار والإعلام وريادة الأعمال في أفريقيا",
    benefit4: "المشاركة في حفل توزيع الجوائز المرموق",
    registerDelegate: "سجل كمندوب",
    enquiries: "الاستفسارات",
    callUs: "اتصل بنا",
    emailUs: "أرسل لنا بريداً إلكترونياً",
    securePayment: "دفع آمن",
    choosePayment: "اختر طريقة الدفع المفضلة لديك لإكمال التسجيل.",
    paybillDetails: "M-Pesa تفاصيل فاتورة الدفع:",
    payNow: "ادفع الآن",
    allTransactionsSecure: "جميع المعاملات آمنة ومشفرة.",
    creditCard: "بطاقة ائتمان / خصم",
    bankTransfer: "تحويل بنكي",
    mpesa: "M-Pesa",
    paypal: "PayPal",
    secureSeat: "احجز مقعدك",
    secureSeatSubtitle: "كن جزءاً من إعادة التصور. اختر مسار حضورك.",
    studentDelegate: "مندوب طالب",
    generalAdmission: "قبول عام",
    virtualDelegate: "مندوب افتراضي",
    perkSessions: "الوصول إلى الجلسات",
    perkBag: "حقيبة المندوب",
    perkCert: "شهادة",
    perkFullAccess: "وصول كامل للجلسات",
    perkDinner: "عشاء تواصل",
    perkLunch: "غداء ووجبات خفيفة",
    perkStream: "وصول للبث المباشر",
    perkWorkbook: "دفتر عمل رقمي",
    perkECert: "شهادة إلكترونية",
    regDetails: "تفاصيل التسجيل",
    firstName: "الاسم الأول",
    lastName: "اسم العائلة",
    emailAddress: "البريد الإلكتروني",
    country: "البلد",
    organization: "المنظمة / الجامعة",
    dietary: "الاحتياجات الغذائية (اختياري)",
    proceedPayment: "المتابعة للدفع",
    regAgreement: "تتم معالجة المدفوعات بشكل آمن. التسجيل يعني الموافقة على شروط الاستخدام ومدونة السلوك الخاصة بنا.",
    footerAbout: "توحيد الشباب الأفريقي لدفع التنمية المستدامة والابتكار العالمي. مبادرة من منصة طلاب الاتحاد الأفريقي.",
    quickLinks: "روابط سريعة",
    contactUs: "اتصل بنا",
    newsletter: "النشرة الإخبارية",
    newsletterDesc: "احصل على آخر تحديثات المتحدثين والإعلانات.",
    emailPlaceholder: "البريد الإلكتروني",
    privacyPolicy: "سياسة الخصوصية",
    termsOfUse: "شروط الاستخدام",
  },
  SW: {
    about: "Kuhusu",
    pillars: "Nguzo",
    program: "Programu",
    pastEvents: "Matukio ya Zamani",
    gallery: "Picha",
    team: "Timu",
    register: "Jisajili",
    registerNow: "Jisajili Sasa",
    conferenceName: "Mkutano wa Kimataifa wa Vijana wa Pan African 2026",
    heroSubtitle: "Kuunganisha vijana wa Pan-African kwa bara la haki, jumuishi na endelevu. Pamoja kuelekea 2063.",
    reimagining: "KUWAZA UPYA",
    africas: "MUSTAKABALI WA",
    future: "AFRIKA",
    visionTitle: "Maono",
    visionHeadline: "Kubadilisha Uwezo Kuwa Nguvu Inayoweza Kutumika",
    visionDescription: "Jukwaa la Wanafunzi wa Umoja wa Afrika (AUSP) ni jumuiya ya bara inayojumuisha zaidi ya nchi 46 za Afrika. Huku 70% ya bara likiwa na umri wa chini ya miaka 30, mkutano huu ni kichocheo cha kubadilisha nishati ya vijana kuwa mabadiliko ya kimfumo.",
    roleTitle: "Wajibu Wetu",
    roleHeadline: "Kuwezesha Sauti ya Bara",
    roleDescription: "AUSP inawakilisha zaidi ya wanafunzi milioni 100. Dhamira yetu imejengwa juu ya nguzo tatu zisizoweza kuvunjika: Elimu, Uhusiano, na Uwezeshaji.",
    statsCountries: "Nchi",
    statsDelegates: "Wajumbe",
    statsImpact: "Athari",
    pillarsHeadline: "NGUZO KUU ZA MABADILIKO",
    pillar1Title: "Ujumuishaji wa Kiuchumi",
    pillar1Desc: "Kuziba pengo la utajiri na kutengeneza fursa endelevu kwa biashara zinazoongozwa na vijana.",
    pillar2Title: "Ubunifu wa Kidijitali",
    pillar2Desc: "Kutumia teknolojia kutatua changamoto za bara na kuendesha mamlaka ya kidijitali.",
    pillar3Title: "Hatua za Tabianchi",
    pillar3Desc: "Kuongoza mapinduzi ya kijani na kulinda urithi wa asili wa Afrika kwa vizazi vijavyo.",
    teamTitle: "Timu Yetu",
    teamHeadline: "Kutana na Wenye Maono",
    teamSubtitle: "Watu waliojitolea wanaofanya kazi bila kuchoka kuunda mustakabali wa uongozi wa vijana wa Afrika.",
    partners: "Washirika",
    partnersTitle: "Washirika na Wafadhili Wetu Wanaoaminika",
    sponsorship: "Udhamini",
    awards: "Tuzo",
    backToHome: "Rudi Nyumbani",
    awardsTitle: "Tuzo za Ubora 2026",
    awardsHeadline: "Tuzo za Ubora za SMEGAfrica 2026",
    awardsSubtitle: "Wito wa Uteuzi - Inasimamiwa na Scholar Media Africa",
    awardsIntro1: "Tuzo za Ubora za SMEGAfrica 2026, zinazosimamiwa na Scholar Media Africa, sasa zimefunguliwa rasmi kwa uteuzi!",
    awardsIntro2: "Jukwaa hili mashuhuri husherehekea watu bora, mashirika, na wabunifu wanaochochea athari, mabadiliko, na ukuaji endelevu kote Afrika.",
    nominationPeriod: "Kipindi cha Uteuzi",
    whoApply: "Nani Anapaswa Kuomba?",
    whoApplyDesc: "Wachochezi wa mabadiliko, wajasiriamali, viongozi wa wanafunzi, au taasisi zinazoleta mabadiliko.",
    whyNominate: "Kwa nini Uteue?",
    whyNominate1: "Onyesha athari yako kwenye jukwaa la bara",
    whyNominate2: "Pata kuonekana miongoni mwa viongozi wa sekta na watunga sera",
    whyNominate3: "Jiunge na mtandao wa wachochezi wa mabadiliko wenye msukumo zaidi barani Afrika",
    submitNomination: "Wasilisha Uteuzi Wako",
    attendDelegate: "Hudhuria kama Mjumbe",
    attendDelegateDesc: "Je, huombi tuzo? Bado unaweza kuwa sehemu ya uzoefu huu wenye athari! Mkutano wa SMEGAfrica unaleta pamoja viongozi wa fikra, wabunifu, wanafunzi, na wataalamu kutoka kote barani kwa ajili ya mitandao, kujifunza, na ushirikiano.",
    delegateBenefits: "Manufaa ya Mjumbe:",
    benefit1: "Ufikiaji wa mijadala ya ngazi ya juu na vikao vikuu",
    benefit2: "Kushirikiana na viongozi wa sekta na watunga sera",
    benefit3: "Maarifa kuhusu uvumbuzi, vyombo vya habari, na ujasiriamali barani Afrika",
    benefit4: "Ushiriki katika sherehe za kifahari za kutoa tuzo",
    registerDelegate: "Jisajili kama Mjumbe",
    enquiries: "Maswali",
    callUs: "Tupigie",
    emailUs: "Tuandikie Barua Pepe",
    securePayment: "Malipo Salama",
    choosePayment: "Chagua njia unayopendelea ya malipo ili kukamilisha usajili.",
    paybillDetails: "Maelezo ya Paybill ya M-Pesa:",
    payNow: "Lipa Sasa",
    allTransactionsSecure: "Miamala yote ni salama na imesimbwa.",
    creditCard: "Kadi ya Mkopo/Akiba",
    bankTransfer: "Hamisho la Benki",
    mpesa: "M-Pesa",
    paypal: "PayPal",
    secureSeat: "Weka Nafasi Yako",
    secureSeatSubtitle: "Kuwa sehemu ya kuwaza upya. Chagua njia yako ya kuhudhuria.",
    studentDelegate: "Mjumbe wa Mwanafunzi",
    generalAdmission: "Kiingilio cha Kawaida",
    virtualDelegate: "Mjumbe wa Mtandaoni",
    perkSessions: "Ufikiaji wa vikao",
    perkBag: "Mfuko wa mjumbe",
    perkCert: "Cheti",
    perkFullAccess: "Ufikiaji kamili wa vikao",
    perkDinner: "Chakula cha jioni cha mtandao",
    perkLunch: "Chakula cha mchana na vitafunio",
    perkStream: "Ufikiaji wa utiririshaji",
    perkWorkbook: "Kitabu cha kazi cha dijiti",
    perkECert: "E-Cheti",
    regDetails: "Maelezo ya Usajili",
    firstName: "Jina la Kwanza",
    lastName: "Jina la Mwisho",
    emailAddress: "Barua Pepe",
    country: "Nchi",
    organization: "Shirika / Chuo Kikuu",
    dietary: "Mahitaji ya Chakula (Hiari)",
    proceedPayment: "Endelea kwenye Malipo",
    regAgreement: "Malipo yanachakatwa kwa usalama. Usajili unamaanisha kukubaliana na Masharti yetu ya matumizi na Kanuni za Maadili.",
    footerAbout: "Kuunganisha vijana wa Afrika ili kuchochea maendeleo endelevu na uvumbuzi wa kimataifa. Mpango wa Jukwaa la Wanafunzi wa Umoja wa Afrika.",
    quickLinks: "Viungo vya Haraka",
    contactUs: "Wasiliana Nasi",
    newsletter: "Jarida",
    newsletterDesc: "Pata sasisho za hivi punde za wasemaji na matangazo.",
    emailPlaceholder: "Barua Pepe",
    privacyPolicy: "Sera ya faragha",
    termsOfUse: "Masharti ya matumizi",
  },
  PT: {
    about: "Sobre",
    pillars: "Pilares",
    program: "Programa",
    pastEvents: "Eventos Passados",
    gallery: "Galeria",
    team: "Equipe",
    register: "Registrar",
    registerNow: "Registre-se Agora",
    conferenceName: "Conferência Internacional da Juventude Pan-Africana 2026",
    heroSubtitle: "Unindo a juventude pan-africana por um continente justo, inclusivo e sustentável. Juntos rumo a 2063.",
    reimagining: "REIMAGINANDO",
    africas: "O FUTURO DA",
    future: "ÁFRICA",
    visionTitle: "A Visão",
    visionHeadline: "Traduzindo Potencial em Poder Acionável",
    visionDescription: "A Plataforma de Estudantes da União Africana (AUSP) é uma comunidade continental que abrange mais de 46 países africanos. Com 70% do continente com menos de 30 anos, esta conferência é o catalisador para traduzir a energia della juventude em mudança sistémica.",
    roleTitle: "Nosso Papel",
    roleHeadline: "Capacitando a Voz Continental",
    roleDescription: "A AUSP representa mais de 100 millions de estudantes. Nossa missione baseia-se em três pilares inquebráveis: Educação, Conexão e Capacitação.",
    statsCountries: "Países",
    statsDelegates: "Delegados",
    statsImpact: "Impacto",
    pillarsHeadline: "PILARES CENTRAIS DE TRANSFORMAÇÃO",
    pillar1Title: "Inclusão Económica",
    pillar1Desc: "Superar o fosso de riqueza e criar oportunidades sustentáveis para empreendimentos liderados por jovens.",
    pillar2Title: "Inovação Digital",
    pillar2Desc: "Aproveitar a tecnologia para resolver desafios continentais e impulsionar a soberania digital.",
    pillar3Title: "Ação Climática",
    pillar3Desc: "Liderar a revolução verde e proteger o património natural de África para as gerações futuras.",
    teamTitle: "Nossa Equipe",
    teamHeadline: "Conheça os Visionários",
    teamSubtitle: "Os indivíduos dedicados que trabalham incansavelmente para moldar o futuro da liderança juvenil africana.",
    partners: "Parceiros",
    partnersTitle: "Nossos Parceiros e Patrocinadores de Confiança",
    sponsorship: "Patrocínio",
    awards: "Prêmios",
    backToHome: "Voltar ao Início",
    awardsTitle: "Prêmios de Excelência 2026",
    awardsHeadline: "Prêmios de Excelência SMEGAfrica 2026",
    awardsSubtitle: "Chamada para Nomeações – Organizado pela Scholar Media Africa",
    awardsIntro1: "Os SMEGAfrica Excellence Awards 2026, organizados pela Scholar Media Africa, estão agora oficialmente abertos para nomeações!",
    awardsIntro2: "Esta prestigiada plataforma celebra indivíduos, organizações e inovadores excepcionais que estão impulsionando o impacto, a transformação e o crescimento sustentável em toda a África.",
    nominationPeriod: "Período de Nomeação",
    whoApply: "Quem Deve se Candidatar?",
    whoApplyDesc: "Agentes de mudança, empreendedores, líderes estudantis ou instituições que fazem a diferença.",
    whyNominate: "Por que Nomear?",
    whyNominate1: "Mostre seu impacto em um palco continental",
    whyNominate2: "Ganhe visibilidade entre líderes da indústria e formuladores de políticas",
    whyNominate3: "Junte-se a uma rede dos agentes de mudança mais inspiradores da África",
    submitNomination: "Envie sua Nomeação",
    attendDelegate: "Participar como Delegado",
    attendDelegateDesc: "Não está se candidatando a um prêmio? Você ainda pode fazer parte desta experiência impactante! A Conferência SMEGAfrica reúne líderes de pensamento, inovadores, estudantes e profissionais de todo o continente para networking, aprendizado e colaboração.",
    delegateBenefits: "Benefícios do Delegado:",
    benefit1: "Acesso a painéis de discussão de alto nível e sessões plenárias",
    benefit2: "Networking with líderes da indústria e formuladores de políticas",
    benefit3: "Insights sobre inovação, mídia e empreendedorismo na África",
    benefit4: "Participação na prestigiosa cerimônia de premiação",
    registerDelegate: "Registrar como Delegado",
    enquiries: "Consultas",
    callUs: "Ligue para Nós",
    emailUs: "Envie-nos um E-mail",
    securePayment: "Pagamento Seguro",
    choosePayment: "Escolha seu método de pagamento preferido para concluir o registro.",
    paybillDetails: "Detalhes do M-Pesa Paybill:",
    payNow: "Pagar Agora",
    allTransactionsSecure: "Todas as transações são seguras e criptografadas.",
    creditCard: "Cartão de Crédito/Débito",
    bankTransfer: "Transferência Bancária",
    mpesa: "M-Pesa",
    paypal: "PayPal",
    secureSeat: "Reserve seu Lugar",
    secureSeatSubtitle: "Faça parte da reimaginação. Escolha seu caminho de participação.",
    studentDelegate: "Delegado Estudantil",
    generalAdmission: "Admissão Geral",
    virtualDelegate: "Delegado Virtual",
    perkSessions: "Acesso às sessões",
    perkBag: "Bolsa do delegado",
    perkCert: "Certificado",
    perkFullAccess: "Acesso total às sessões",
    perkDinner: "Jantar de networking",
    perkLunch: "Almoço e lanches",
    perkStream: "Acesso ao streaming",
    perkWorkbook: "Caderno de exercícios digital",
    perkECert: "E-Certificado",
    regDetails: "Detalhes do Registro",
    firstName: "Primeiro Nome",
    lastName: "Sobrenome",
    emailAddress: "Endereço de E-mail",
    country: "País",
    organization: "Organização / Universidade",
    dietary: "Requisitos Dietéticos (Opcional)",
    proceedPayment: "Prosseguir para o Pagamento",
    regAgreement: "Os pagamentos são processados com segurança. O registro implica a aceitação dos nossos Termos de uso e Código de Conduta.",
    footerAbout: "Unindo a juventude africana para impulsionar o desenvolvimento sustentável e a inovação global. Uma iniciativa da Plataforma de Estudantes da União Africana.",
    quickLinks: "Links Rápidos",
    contactUs: "Contate-nos",
    newsletter: "Boletim Informativo",
    newsletterDesc: "Receba as últimas atualizações de palestrantes e anúncios.",
    emailPlaceholder: "Endereço de E-mail",
    privacyPolicy: "Política de privacidade",
    termsOfUse: "Termos de uso",
  }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('EN')

  const t = (key: string) => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
